FROM guacamole/guacd:1.0.0

LABEL maintainer="Support@Quali.com" url="https://support.quali.com"

#The default value is info (optional value: debug)
ENV GUACD_LOG_LEVEL=info 

# guacd port
# IMPORTANT >>> DONT EXPOSE IN PRODUCTION
# EXPOSE 4822
